-- AlterTable
ALTER TABLE "Level" ADD COLUMN     "onGoingTime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "penalities" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "onGoingTime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "penalities" INTEGER NOT NULL DEFAULT 0;
